"""Build Level-2 institution-behavior evidence from single-stock ops data."""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path

import numpy as np
import pandas as pd


@dataclass(frozen=True)
class BehaviorThresholds:
    """Thresholds for classifying institution-like behavior days."""

    large_op_wan: float = 500.0
    super_op_wan: float = 2000.0
    strong_net_buy_wan: float = 1000.0
    strong_net_sell_wan: float = -1000.0
    instant_span_min: float = 0.5
    small_slice_wan: float = 100.0
    min_slice_orders: int = 10


def load_ops(single_stock_dir: Path) -> pd.DataFrame:
    """Load operation clusters generated by the single-stock Level-2 pipeline."""
    path = single_stock_dir / "ops" / "all_ops.csv"
    if not path.exists():
        raise FileNotFoundError(f"ops file not found: {path}")

    ops = pd.read_csv(path)
    required = {
        "date",
        "direction",
        "total_amount_wan",
        "avg_price",
        "order_count",
        "time_span_min",
        "start_time",
        "end_time",
        "avg_order_size_wan",
        "vwap_deviation_pct",
        "order_hhi",
    }
    missing = required - set(ops.columns)
    if missing:
        raise ValueError(f"ops file missing columns: {sorted(missing)}")

    ops = ops.copy()
    ops["date"] = ops["date"].astype(str)
    for col in [
        "total_amount_wan",
        "avg_price",
        "order_count",
        "time_span_min",
        "start_time",
        "end_time",
        "avg_order_size_wan",
        "vwap_deviation_pct",
        "order_hhi",
    ]:
        ops[col] = pd.to_numeric(ops[col], errors="coerce")
    ops["direction"] = ops["direction"].astype(str).str.upper()
    return ops


def _time_label(seconds: float | int | None) -> str:
    if pd.isna(seconds):
        return ""
    seconds = int(seconds)
    h = seconds // 3600
    m = (seconds % 3600) // 60
    s = seconds % 60
    return f"{h:02d}:{m:02d}:{s:02d}"


def _classify_day(row: pd.Series) -> tuple[str, int]:
    """Return behavior type and confidence score."""
    buy_ratio = row.get("buy_ratio", np.nan)
    net_wan = row.get("net_wan", 0.0)
    n_super_buy = row.get("n_super_buy", 0)
    n_super_sell = row.get("n_super_sell", 0)
    n_large_buy = row.get("n_large_buy", 0)
    n_large_sell = row.get("n_large_sell", 0)
    instant_ratio = row.get("instant_ratio", 0.0)
    small_slice_ratio = row.get("small_slice_ratio", 0.0)

    if n_super_buy > 0 and buy_ratio >= 0.75:
        score = 95 if instant_ratio >= 0.7 else 90
        return "超级买入扫货/集中建仓", score
    if n_super_sell > 0 and buy_ratio <= 0.35:
        score = 94 if instant_ratio >= 0.5 else 88
        return "超级卖出/集中出货", score
    if n_large_buy >= 3 and net_wan > 0 and buy_ratio >= 0.65:
        return "多簇买入推进", 82
    if n_large_sell >= 3 and net_wan < 0 and buy_ratio <= 0.4:
        return "多簇卖出压盘", 82
    if instant_ratio >= 0.75 and row.get("max_op_wan", 0) >= 500:
        return "瞬时冲击型大单", 76
    if small_slice_ratio >= 0.5:
        return "算法拆单型", 70
    if net_wan >= 1000:
        return "温和净买入", 62
    if net_wan <= -1000:
        return "温和净卖出", 62
    return "普通/混合", 45


def summarize_behavior(
    ops: pd.DataFrame,
    thresholds: BehaviorThresholds | None = None,
) -> tuple[pd.DataFrame, pd.DataFrame]:
    """Aggregate operation clusters into daily institution-behavior evidence."""
    thresholds = thresholds or BehaviorThresholds()
    frame = ops.copy()
    frame["is_buy"] = frame["direction"].eq("BUY")
    frame["is_sell"] = frame["direction"].eq("SELL")
    frame["is_large"] = frame["total_amount_wan"] >= thresholds.large_op_wan
    frame["is_super"] = frame["total_amount_wan"] >= thresholds.super_op_wan
    frame["is_instant"] = frame["time_span_min"] <= thresholds.instant_span_min
    frame["is_small_slice"] = (
        (frame["order_count"] >= thresholds.min_slice_orders)
        & (frame["avg_order_size_wan"] < thresholds.small_slice_wan)
    )

    grouped = frame.groupby("date", sort=True)
    rows: list[dict] = []
    for date, day in grouped:
        buy = day.loc[day["is_buy"], "total_amount_wan"].sum()
        sell = day.loc[day["is_sell"], "total_amount_wan"].sum()
        gross = buy + sell
        max_idx = day["total_amount_wan"].idxmax()
        max_op = day.loc[max_idx]
        top_ops = day.sort_values("total_amount_wan", ascending=False).head(3)
        top_desc = []
        for _, op in top_ops.iterrows():
            top_desc.append(
                f"{op['direction']} {op['total_amount_wan']:.0f}万@{op['avg_price']:.2f}"
                f" x{int(op['order_count'])} {_time_label(op['start_time'])}"
            )

        row = {
            "date": date,
            "buy_wan": round(float(buy), 2),
            "sell_wan": round(float(sell), 2),
            "net_wan": round(float(buy - sell), 2),
            "gross_wan": round(float(gross), 2),
            "buy_ratio": round(float(buy / gross), 4) if gross else np.nan,
            "n_ops": int(len(day)),
            "n_large_buy": int((day["is_large"] & day["is_buy"]).sum()),
            "n_large_sell": int((day["is_large"] & day["is_sell"]).sum()),
            "n_super_buy": int((day["is_super"] & day["is_buy"]).sum()),
            "n_super_sell": int((day["is_super"] & day["is_sell"]).sum()),
            "instant_ratio": round(float(day["is_instant"].mean()), 4),
            "small_slice_ratio": round(float(day["is_small_slice"].mean()), 4),
            "max_op_wan": round(float(max_op["total_amount_wan"]), 2),
            "max_op_direction": str(max_op["direction"]),
            "max_op_price": round(float(max_op["avg_price"]), 4),
            "max_op_orders": int(max_op["order_count"]),
            "max_op_start": _time_label(max_op["start_time"]),
            "max_op_span_min": round(float(max_op["time_span_min"]), 2),
            "max_op_vwap_dev_pct": round(float(max_op["vwap_deviation_pct"]), 2),
            "avg_order_hhi": round(float(day["order_hhi"].mean()), 4),
            "top_ops": " | ".join(top_desc),
        }
        behavior_type, confidence = _classify_day(pd.Series(row))
        row["behavior_type"] = behavior_type
        row["behavior_confidence"] = confidence
        rows.append(row)

    daily = pd.DataFrame(rows)
    notable = daily[
        (daily["n_super_buy"] > 0)
        | (daily["n_super_sell"] > 0)
        | (daily["n_large_buy"] >= 3)
        | (daily["n_large_sell"] >= 3)
        | (daily["net_wan"] >= thresholds.strong_net_buy_wan)
        | (daily["net_wan"] <= thresholds.strong_net_sell_wan)
    ].copy()
    return daily, notable
